version: "3.8"
services:
  flaskapp:
    build: .
    image: flaskapp
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
